### PR TITLE
Fix name of getMultilingualFile method

### PR DESCRIPTION
**Pull request by mattpardee**
The "Multilingual" part of the method name is actually all lowercase

### CODE REVIEW

**Comment by kdzwinel** [comment]
🤦‍♂️ Thanks for catching that and reporting! This will be a very disappointing 2.0 release.

**Comment by kdzwinel** [comment]
Wait, it's only the docs that are wrong! Phew!!! Thanks a bunch!

**Comment by mattpardee** [comment]
No problem! Thank you for making the module!

**Comment by SebastianCzoch** [comment]
@mattpardee Thanks for your contribution!

**Pull request merged**
