### PR TITLE
MD5 is deprecated. Use md5 as replacement

### PR DESCRIPTION
**Pull request by quanglam2807**

### CODE REVIEW

**Comment by kdzwinel** [comment]
Thanks for a contribution! Can you please also update this: https://github.com/brainly/nodejs-onesky-utils/blob/master/lib/privateFunctions.js#L10 so that tests pass?

**Comment by quanglam2807** [comment]
@kdzwinel  Done :dancer:

**Comment by kdzwinel** [comment]
LGTM

@mr-mig , @SebastianCzoch ?

**Comment by SebastianCzoch** [comment]
LGTM

**Comment by quanglam2807** [comment]
LOL, guys! It's just too small for the whole team to cheer me :100:

**Comment by kdzwinel** [comment]
You took time to fix it, you definitely deserve some high fives :)

Please update version in package file to 0.0.3 (I missed that, sorry!) and we will :ship: it :+1:

**Comment by SebastianCzoch** [comment]
@kdzwinel @quanglam2807 so, I'm going to merge it and set new version of lib for npm

**Comment by quanglam2807** [comment]
@kdzwinel @SebastianCzoch Nice, guys! Superb!

**Comment by SebastianCzoch** [comment]
@quanglam2807 welcome :)

**Pull request merged**
