### PR TITLE
Remove trailing slash in apiAddress global variable

### PR DESCRIPTION
**Pull request by skolodyazhnyy**
Each API call already adds leading slash to the address, like so:

```javascript
function _getUploadOptions (options) {
  return {
    method: 'POST',
    url: apiAddress + '/1/projects/' + options.projectId ...
```

This results in double slash `https://platform.api.onesky.io//1/projects/...`.

Until recently it wasn't a problem, but OneSky started redirecting these calls to `http://www.oneskyapp.com//1/projects/...` so whole thing fails with a cryptic error.

### CODE REVIEW

**Comment by Thomas-Rosenkrans-Vestergaard** [comment]
:+1: :heart:

**Comment by sarsonj** [comment]
+1 - I spend half day to realise, why my scripts stop working. Please allow merge to main branch.

**Review by krzotki — APPROVED** [review]

**Review by matzimowski — APPROVED** [review]

**Comment by dr-bizz** [comment]
When will this be merged into the master branch and published on NPM?

**Comment by krzotki** [comment]
> When will this be merged into the master branch and published on NPM?

Once this PR is merged: https://github.com/brainly/nodejs-onesky-utils/pull/63

**Pull request merged**
